# Generated by Django 5.0.7 on 2024-07-18 19:10

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="schedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Task", models.CharField(max_length=40)),
                ("Descirption", models.CharField(max_length=200)),
                ("Priority", models.CharField(max_length=6)),
                ("DueDate", models.CharField(max_length=10)),
                ("Status", models.CharField(max_length=15)),
            ],
        ),
    ]
