# Generated by Django 5.0.7 on 2024-07-18 19:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("quiz", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="schedule",
            old_name="Descirption",
            new_name="Description",
        ),
    ]
